### PR TITLE
Update meta.yaml for 0.5.2

### PR DESCRIPTION
**Pull request by abstractqqq**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

First time updating conda feedstock. Please review and let me know if there is anything else I need to do. I updated the version and the sha256

### CODE REVIEW

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please restart ci

**Comment by thewchan** [comment]
@xhochy @abstractqqq Perhaps we favor https://github.com/conda-forge/polars-ds-feedstock/pull/24 instead?

**Comment by abstractqqq** [comment]
> @xhochy @abstractqqq Perhaps we favor #24 instead?

yes let's go with that. Btw, how do you track whether the auto-tick bot has run or not?

**Comment by thewchan** [comment]
@abstractqqq I don't really check tbh; usually the bot will run within a day or 2 depending

**Comment by xhochy** [comment]
You can look it up on https://conda-forge.org/status

**Comment by abstractqqq** [comment]
> You can look it up on https://conda-forge.org/status

Got it. Thank you guys

**Pull request closed without merging**
